@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.altnoir.mementoinabyss.util.concurrent;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
