plugins {
    id 'java-library'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'idea'
    id 'net.kyori.blossom' version '2.2.0'
    id 'me.modmuss50.mod-publish-plugin' version '1.1.0'
    id 'org.jetbrains.gradle.plugin.idea-ext' version '1.4.1'
    id 'io.freefair.lombok' version "9.5.0"
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

def release = providers.environmentVariable("RELEASE")
boolean dev = !release.map { it.toBoolean() }.getOrElse(false)

def gitHash = providers.exec {
    commandLine 'git', 'rev-parse', '--short', 'HEAD'
}.standardOutput.asText.map { it.trim() }.getOrElse("dev")

version = mod_version
group = mod_group_id

sourceSets.main {
    resources {
        srcDir('src/generated/resources')
        exclude("**/*.bbmodel") // BlockBench project files
        exclude("**/.cache") // datagen cache files
    }
    blossom.javaSources {
        property 'version', mod_version
        property 'gitCommit', gitHash
    }
}

repositories {
    maven { url = "https://maven.gegy.dev/releases" } // Registrate
    maven { url = "https://api.modrinth.com/maven" } // Jade
    maven { url = "https://maven.blamejared.com/" } // JEI, Patchouli
    maven { url = "https://maven.theillusivec4.top/" } // Curios
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)
java.withSourcesJar()
java.withJavadocJar()

neoForge {
    version = project.neo_version
    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            clientData()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

jar {
    manifest {
        attributes([
                'Specification-Title'     : mod_name,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : project.jar.archiveVersion,
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                'Timestampe'              : System.currentTimeMillis(),
                'Built-On-Java'           : "${System.getProperty('java.vm.version')} (${System.getProperty('java.vm.vendor')})",
                'Built-On-Minecraft'      : minecraft_version,
                "MixinConfigs"            : "mia.mixins.json",
                "Git-Hash"                : gitHash
        ])
    }
}

javadoc {
    options.addStringOption('Xdoclint:none', '-quiet')
}

tasks.named("sourcesJar", Jar) {
    manifest.attributes([
            "Git-Hash": gitHash
    ])
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation jarJar("com.tterrag.registrate:Registrate:${registrate_version}")

    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    implementation "maven.modrinth:jade:${jade_version}"
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_authors            : mod_authors,
            mod_license            : mod_license,
            mod_version            : mod_version,
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

publishMods {
    file = jar.archiveFile
    type = ALPHA
    version = "$mod_version+mc$minecraft_version"
    displayName = "$mod_name $mod_version for mc$minecraft_version"
    modLoaders.add("neoforge")

    github {
        repository = "MIA-Development-Team/Made-In-Abyss"
        accessToken = providers.environmentVariable("GITHUB_TOKEN")
        commitish = gitHash
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
