org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.78

## Mod Properties
mod_id=mementoinabyss
mod_name=Memento In Abyss
mod_license=MIT
mod_version=0.1.0.alpha.0
mod_group_id=com.altnoir.mementoinabyss
mod_authors=Altnoir, RingLo_, zljtt, zhaijineet

## Dependencies
registrate_version=MC26.1-1.5.7
jei_version=29.12.0.40
curios_version=15.0.0-beta.2+26.1.2
jade_version=26.1.8+neoforge
fzzyconfig_version=0.7.6+26.1+neoforge
sodium_version=0.9.1+mc26.1.2
