@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.altnoir.mementoinabyss.foundation.transfer;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
