@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault

package com.altnoir.mementoinabyss.impl.registrate;

import com.mojang.logging.annotations.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;